---
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer-app
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: assisted-installer-app
    spec:
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Assisted Installer
      deploymentRepo: https://github.com/openshift-assisted/assisted-installer-ui
      frontend:
        paths:
          - /apps/assisted-installer-app
      image: ${IMAGE}:${IMAGE_TAG}

      module:
        manifestLocation: '/apps/frontend-starter-app/fed-mods.json'
        modules:
          - id: 'overview'
            module: './RootApp'
            routes:
              - pathname: /openshift/assisted-installer-app

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/app-sre/assisted-installer-app
